import type { CardProps } from "./types";

export const CARDS: CardProps[] = [
    { suit: 'spade', rank: 'A', id: 's-A', isOpen: false },
    { suit: 'spade', rank: '2', id: 's-2', isOpen: false },
    { suit: 'spade', rank: '3', id: 's-3', isOpen: false },
    { suit: 'spade', rank: '4', id: 's-4', isOpen: false },
    { suit: 'spade', rank: '5', id: 's-5', isOpen: false },
    { suit: 'spade', rank: '6', id: 's-6', isOpen: false },
    { suit: 'spade', rank: '7', id: 's-7', isOpen: false },
    { suit: 'spade', rank: '8', id: 's-8', isOpen: false },
    { suit: 'spade', rank: '9', id: 's-9', isOpen: false },
    { suit: 'spade', rank: '10', id: 's-10', isOpen: false },
    { suit: 'spade', rank: 'J', id: 's-J', isOpen: false },
    { suit: 'spade', rank: 'Q', id: 's-Q', isOpen: false },
    { suit: 'spade', rank: 'K', id: 's-K', isOpen: false },
    { suit: 'heart', rank: 'A', id: 'h-A', isOpen: false },
    { suit: 'heart', rank: '2', id: 'h-2', isOpen: false },
    { suit: 'heart', rank: '3', id: 'h-3', isOpen: false },
    { suit: 'heart', rank: '4', id: 'h-4', isOpen: false },
    { suit: 'heart', rank: '5', id: 'h-5', isOpen: false },
    { suit: 'heart', rank: '6', id: 'h-6', isOpen: false },
    { suit: 'heart', rank: '7', id: 'h-7', isOpen: false },
    { suit: 'heart', rank: '8', id: 'h-8', isOpen: false },
    { suit: 'heart', rank: '9', id: 'h-9', isOpen: false },
    { suit: 'heart', rank: '10', id: 'h-10', isOpen: false },
    { suit: 'heart', rank: 'J', id: 'h-J', isOpen: false },
    { suit: 'heart', rank: 'Q', id: 'h-Q', isOpen: false },
    { suit: 'heart', rank: 'K', id: 'h-K', isOpen: false },
    { suit: 'club', rank: 'A', id: 'c-A', isOpen: false },
    { suit: 'club', rank: '2', id: 'c-2', isOpen: false },
    { suit: 'club', rank: '3', id: 'c-3', isOpen: false },
    { suit: 'club', rank: '4', id: 'c-4', isOpen: false },
    { suit: 'club', rank: '5', id: 'c-5', isOpen: false },
    { suit: 'club', rank: '6', id: 'c-6', isOpen: false },
    { suit: 'club', rank: '7', id: 'c-7', isOpen: false },
    { suit: 'club', rank: '8', id: 'c-8', isOpen: false },
    { suit: 'club', rank: '9', id: 'c-9', isOpen: false },
    { suit: 'club', rank: '10', id: 'c-10', isOpen: false },
    { suit: 'club', rank: 'J', id: 'c-J', isOpen: false },
    { suit: 'club', rank: 'Q', id: 'c-Q', isOpen: false },
    { suit: 'club', rank: 'K', id: 'c-K', isOpen: false },
    { suit: 'diamond', rank: 'A', id: 'd-A', isOpen: false },
    { suit: 'diamond', rank: '2', id: 'd-2', isOpen: false },
    { suit: 'diamond', rank: '3', id: 'd-3', isOpen: false },
    { suit: 'diamond', rank: '4', id: 'd-4', isOpen: false },
    { suit: 'diamond', rank: '5', id: 'd-5', isOpen: false },
    { suit: 'diamond', rank: '6', id: 'd-6', isOpen: false },
    { suit: 'diamond', rank: '7', id: 'd-7', isOpen: false },
    { suit: 'diamond', rank: '8', id: 'd-8', isOpen: false },
    { suit: 'diamond', rank: '9', id: 'd-9', isOpen: false },
    { suit: 'diamond', rank: '10', id: 'd-10', isOpen: false },
    { suit: 'diamond', rank: 'J', id: 'd-J', isOpen: false },
    { suit: 'diamond', rank: 'Q', id: 'd-Q', isOpen: false },
    { suit: 'diamond', rank: 'K', id: 'd-K', isOpen: false },
];

export const TEST_STACK_COMPLETE: CardProps[] = [
    { suit: 'spade', rank: 'K', id: '1', isOpen: false },
    { suit: 'diamond', rank: 'Q', id: '2', isOpen: false },
    { suit: 'spade', rank: 'J', id: '3', isOpen: false },
    { suit: 'diamond', rank: '10', id: '4', isOpen: false },
    { suit: 'spade', rank: '9', id: '5', isOpen: false },
    { suit: 'diamond', rank: '8', id: '6', isOpen: false },
    { suit: 'spade', rank: '7', id: '7', isOpen: false },
    { suit: 'diamond', rank: '6', id: '8', isOpen: false },
    { suit: 'spade', rank: '5', id: '9', isOpen: false },
    { suit: 'diamond', rank: '4', id: '10', isOpen: false },
    { suit: 'spade', rank: '3', id: '11', isOpen: false },
    { suit: 'diamond', rank: '2', id: '12', isOpen: false },
    { suit: 'spade', rank: 'A', id: '13', isOpen: false },
];

export const suitLetterMap = {
    'h': 'heart',
    'd': 'diamond',
    'c': 'club',
    's': 'spade',
};

export const rankWeightMap = {
    'A': 1,
    '2': 2,
    '3': 3,
    '4': 4,
    '5': 5,
    '6': 6,
    '7': 7,
    '8': 8,
    '9': 9,
    '10': 10,
    'J': 11,
    'Q': 12,
    'K': 13,
};

export const dropZonehighlight = '2px dashed red';

export const TEST_STATE_1: Record<string, CardProps[]> = {
    'pile-1': [
        { suit: 'heart', rank: 'A', id: 'h-A', isOpen: true },
    ],
    'pile-2': [
        { suit: 'diamond', rank: 'A', id: 'd-A', isOpen: true },
    ],
    'pile-3': [],
    'pile-4': [],
    'pile-5': [],
    'pile-6': [
        { suit: 'spade', rank: 'K', id: 's-K', isOpen: true },
        { suit: 'diamond', rank: 'Q', id: 'd-Q', isOpen: true },
        { suit: 'spade', rank: 'J', id: 's-J', isOpen: true },
        { suit: 'diamond', rank: '10', id: 'd-10', isOpen: true },
        { suit: 'spade', rank: '9', id: 's-9', isOpen: true },
        { suit: 'diamond', rank: '8', id: 'd-8', isOpen: true },
        { suit: 'spade', rank: '7', id: 's-7', isOpen: true },
        { suit: 'diamond', rank: '6', id: 'd-6', isOpen: true },
        { suit: 'spade', rank: '5', id: 's-5', isOpen: true },
        { suit: 'diamond', rank: '4', id: 'd-4', isOpen: true },
        { suit: 'spade', rank: '3', id: 's-3', isOpen: true },
        { suit: 'diamond', rank: '2', id: 'd-2', isOpen: true },
    ],
    'pile-7': [
        { suit: 'diamond', rank: 'K', id: 'd-K', isOpen: true },
        { suit: 'spade', rank: 'Q', id: 's-Q', isOpen: true },
        { suit: 'diamond', rank: 'J', id: 'd-J', isOpen: true },
        { suit: 'spade', rank: '10', id: 's-10', isOpen: true },
        { suit: 'diamond', rank: '9', id: 'd-9', isOpen: true },
        { suit: 'spade', rank: '8', id: 's-8', isOpen: true },
        { suit: 'diamond', rank: '7', id: 'd-7', isOpen: true },
        { suit: 'spade', rank: '6', id: 's-6', isOpen: true },
        { suit: 'diamond', rank: '5', id: 'd-5', isOpen: true },
        { suit: 'spade', rank: '4', id: 's-4', isOpen: true },
        { suit: 'diamond', rank: '3', id: 'd-3', isOpen: true },
        { suit: 'spade', rank: '2', id: 's-2', isOpen: true },
    ],
    // Talon
    'talon': [
        { suit: 'club', rank: '2', id: 'c-2', isOpen: false },
        { suit: 'spade', rank: '3', id: 's-3', isOpen: false },
        { suit: 'spade', rank: '4', id: 's-4', isOpen: false },
        { suit: 'spade', rank: '5', id: 's-5', isOpen: false },
        { suit: 'spade', rank: '6', id: 's-6', isOpen: false },
        { suit: 'spade', rank: '7', id: 's-7', isOpen: false },
        { suit: 'spade', rank: '8', id: 's-8', isOpen: false },
        { suit: 'spade', rank: '9', id: 's-9', isOpen: false },
        { suit: 'spade', rank: '10', id: 's-10', isOpen: false },
        { suit: 'spade', rank: 'Q', id: 's-Q', isOpen: false },
        { suit: 'spade', rank: 'A', id: 's-A', isOpen: false },
        { suit: 'club', rank: 'A', id: 'c-A', isOpen: false },
        { suit: 'spade', rank: 'J', id: 's-J', isOpen: false },
        { suit: 'spade', rank: 'K', id: 's-K', isOpen: false },
    ],
    // Foundations
    'foundation-1': [],
    'foundation-2': [],
    'foundation-3': [],
    'foundation-4': [],
};

export const TEST_STATE_2: Record<string, CardProps[]> = {
    'pile-1': [
        // { suit: 'heart', rank: 'A', id: 'h-A', isOpen: true },
    ],
    'pile-2': [
        // { suit: 'diamond', rank: 'A', id: 'd-A', isOpen: true },
    ],
    'pile-3': [],
    'pile-4': [],
    'pile-5': [],
    'pile-6': [
        { suit: 'club', rank: '2', id: 's-2', isOpen: true },
    ],
    'pile-7': [
        { suit: 'spade', rank: '2', id: 's-2', isOpen: true },
    ],
    // Talon
    'talon': [
        { suit: 'club', rank: '5', id: '5-A', isOpen: false },
        { suit: 'spade', rank: 'A', id: 's-A', isOpen: false },
        { suit: 'club', rank: 'A', id: 'c-A', isOpen: false },
    ],
    // Foundations
    'foundation-1': [],
    'foundation-2': [],
    'foundation-3': [],
    'foundation-4': [],
};

export const TEST_STATE_COMPLETE: Record<string, CardProps[]> = {
    'pile-1': [],
    'pile-2': [],
    'pile-3': [],
    'pile-4': [],
    'pile-5': [],
    'pile-6': [],
    'pile-7': [],
    // Talon
    'talon': [],
    // Foundations
    'foundation-1': [
        { suit: 'spade', rank: 'A', id: 's-A', isOpen: true },
        { suit: 'spade', rank: '2', id: 's-2', isOpen: true },
        { suit: 'spade', rank: '3', id: 's-3', isOpen: true },
        { suit: 'spade', rank: '4', id: 's-4', isOpen: true },
        { suit: 'spade', rank: '5', id: 's-5', isOpen: true },
        { suit: 'spade', rank: '6', id: 's-6', isOpen: true },
        { suit: 'spade', rank: '7', id: 's-7', isOpen: true },
        { suit: 'spade', rank: '8', id: 's-8', isOpen: true },
        { suit: 'spade', rank: '9', id: 's-9', isOpen: true },
        { suit: 'spade', rank: '10', id: 's-10', isOpen: true },
        { suit: 'spade', rank: 'J', id: 's-J', isOpen: true },
        { suit: 'spade', rank: 'Q', id: 's-Q', isOpen: true },
        { suit: 'spade', rank: 'K', id: 's-K', isOpen: true },
    ],
    'foundation-2': [
        { suit: 'diamond', rank: 'A', id: 'd-A', isOpen: true },
        { suit: 'diamond', rank: '2', id: 'd-2', isOpen: true },
        { suit: 'diamond', rank: '3', id: 'd-3', isOpen: true },
        { suit: 'diamond', rank: '4', id: 'd-4', isOpen: true },
        { suit: 'diamond', rank: '5', id: 'd-5', isOpen: true },
        { suit: 'diamond', rank: '6', id: 'd-6', isOpen: true },
        { suit: 'diamond', rank: '7', id: 'd-7', isOpen: true },
        { suit: 'diamond', rank: '8', id: 'd-8', isOpen: true },
        { suit: 'diamond', rank: '9', id: 'd-9', isOpen: true },
        { suit: 'diamond', rank: '10', id: 'd-10', isOpen: true },
        { suit: 'diamond', rank: 'J', id: 'd-J', isOpen: true },
        { suit: 'diamond', rank: 'Q', id: 'd-Q', isOpen: true },
        { suit: 'diamond', rank: 'K', id: 'd-K', isOpen: true },
    ],
    'foundation-3': [
        { suit: 'club', rank: 'A', id: 'c-A', isOpen: true },
        { suit: 'club', rank: '2', id: 'c-2', isOpen: true },
        { suit: 'club', rank: '3', id: 'c-3', isOpen: true },
        { suit: 'club', rank: '4', id: 'c-4', isOpen: true },
        { suit: 'club', rank: '5', id: 'c-5', isOpen: true },
        { suit: 'club', rank: '6', id: 'c-6', isOpen: true },
        { suit: 'club', rank: '7', id: 'c-7', isOpen: true },
        { suit: 'club', rank: '8', id: 'c-8', isOpen: true },
        { suit: 'club', rank: '9', id: 'c-9', isOpen: true },
        { suit: 'club', rank: '10', id: 'c-10', isOpen: true },
        { suit: 'club', rank: 'J', id: 'c-J', isOpen: true },
        { suit: 'club', rank: 'Q', id: 'c-Q', isOpen: true },
        { suit: 'club', rank: 'K', id: 'c-K', isOpen: true },
    ],
    'foundation-4': [
        { suit: 'heart', rank: 'A', id: 'h-A', isOpen: true },
        { suit: 'heart', rank: '2', id: 'h-2', isOpen: true },
        { suit: 'heart', rank: '3', id: 'h-3', isOpen: true },
        { suit: 'heart', rank: '4', id: 'h-4', isOpen: true },
        { suit: 'heart', rank: '5', id: 'h-5', isOpen: true },
        { suit: 'heart', rank: '6', id: 'h-6', isOpen: true },
        { suit: 'heart', rank: '7', id: 'h-7', isOpen: true },
        { suit: 'heart', rank: '8', id: 'h-8', isOpen: true },
        { suit: 'heart', rank: '9', id: 'h-9', isOpen: true },
        { suit: 'heart', rank: '10', id: 'h-10', isOpen: true },
        { suit: 'heart', rank: 'J', id: 'h-J', isOpen: true },
        { suit: 'heart', rank: 'Q', id: 'h-Q', isOpen: true },
        { suit: 'heart', rank: 'K', id: 'h-K', isOpen: true },
    ],
};

export const TEST_STATE_3: Record<string, CardProps[]> = {
    'pile-1': [
        { suit: 'diamond', rank: 'A', id: 'd-A', isOpen: true },
        { suit: 'spade', rank: 'A', id: 's-A', isOpen: false },
    ],
    'pile-2': [
        // { suit: 'spade', rank: 'A', id: 's-A', isOpen: true },
    ],
    'pile-3': [],
    'pile-4': [],
    'pile-5': [],
    'pile-6': [
        // { suit: 'spade', rank: 'K', id: 's-K', isOpen: false },
        // { suit: 'diamond', rank: 'Q', id: 'd-Q', isOpen: false },
        // { suit: 'spade', rank: 'J', id: 's-J', isOpen: false },
        // { suit: 'diamond', rank: '10', id: 'd-10', isOpen: true },
        // { suit: 'spade', rank: '9', id: 's-9', isOpen: true },
        // { suit: 'diamond', rank: '8', id: 'd-8', isOpen: true },
        // { suit: 'spade', rank: '7', id: 's-7', isOpen: true },
        // { suit: 'diamond', rank: '6', id: 'd-6', isOpen: true },
        // { suit: 'spade', rank: '5', id: 's-5', isOpen: true },
        // { suit: 'diamond', rank: '4', id: 'd-4', isOpen: true },
        // { suit: 'spade', rank: '3', id: 's-3', isOpen: true },
        // { suit: 'diamond', rank: '2', id: 'd-2', isOpen: true },
    ],
    'pile-7': [
        // { suit: 'diamond', rank: 'K', id: 'd-K', isOpen: false },
        // { suit: 'spade', rank: 'Q', id: 's-Q', isOpen: false },
        // { suit: 'diamond', rank: 'J', id: 'd-J', isOpen: false },
        // { suit: 'spade', rank: '10', id: 's-10', isOpen: true },
        // { suit: 'diamond', rank: '9', id: 'd-9', isOpen: true },
        // { suit: 'spade', rank: '8', id: 's-8', isOpen: true },
        // { suit: 'diamond', rank: '7', id: 'd-7', isOpen: true },
        // { suit: 'spade', rank: '6', id: 's-6', isOpen: true },
        // { suit: 'diamond', rank: '5', id: 'd-5', isOpen: true },
        // { suit: 'spade', rank: '4', id: 's-4', isOpen: true },
        // { suit: 'diamond', rank: '3', id: 'd-3', isOpen: true },
        // { suit: 'spade', rank: '2', id: 's-2', isOpen: true },
    ],
    // Talon
    'talon': [
        // { suit: 'club', rank: '3', id: 'c-3', isOpen: false },
        // { suit: 'diamond', rank: 'A', id: 'd-A', isOpen: false },
        // { suit: 'spade', rank: 'A', id: 's-A', isOpen: false },
        { suit: 'heart', rank: 'A', id: 'h-A', isOpen: false },
        { suit: 'heart', rank: '2', id: 'h-2', isOpen: false },
        { suit: 'heart', rank: '3', id: 'h-3', isOpen: false },
        { suit: 'heart', rank: '4', id: 'h-4', isOpen: false },
        { suit: 'heart', rank: '5', id: 'h-5', isOpen: false },
        { suit: 'heart', rank: '6', id: 'h-6', isOpen: false },
        { suit: 'heart', rank: '7', id: 'h-7', isOpen: false },
        { suit: 'heart', rank: '8', id: 'h-8', isOpen: false },
        { suit: 'heart', rank: '9', id: 'h-9', isOpen: false },
        { suit: 'heart', rank: '10', id: 'h-10', isOpen: false },
        { suit: 'heart', rank: 'J', id: 'h-J', isOpen: false },
        { suit: 'heart', rank: 'Q', id: 'h-Q', isOpen: false },
        { suit: 'heart', rank: 'K', id: 'h-K', isOpen: false },
        // { suit: 'spade', rank: 'A', id: 's-A', isOpen: false },
        // { suit: 'club', rank: 'A', id: 'c-A', isOpen: false },
    ],
    // Foundations
    'foundation-1': [],
    'foundation-2': [],
    'foundation-3': [],
    'foundation-4': [],
};

export const TEST_STATE_EMPTY: Record<string, CardProps[]> = {
    'pile-1': [],
    'pile-2': [],
    'pile-3': [],
    'pile-4': [],
    'pile-5': [],
    'pile-6': [],
    'pile-7': [],
    // Talon
    'talon': [],
    // Foundations
    'foundation-1': [],
    'foundation-2': [],
    'foundation-3': [],
    'foundation-4': [],
};

export const CARD_MOVEMENT_DURATION = 400;
